# Generated by Django 3.2.7 on 2021-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('donation_id', models.CharField(editable=False, max_length=32)),
            ],
        ),
    ]
