# Generated by Django 3.2.7 on 2021-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='donation_id',
            field=models.CharField(default=13245, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
