# Generated by Django 3.2.7 on 2021-09-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='volunteers',
            options={'verbose_name': 'Volunteers'},
        ),
    ]
