# Generated by Django 3.2.7 on 2021-09-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210922_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={},
        ),
    ]
