# Generated by Django 3.2.7 on 2021-09-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210922_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField(max_length=400)),
            ],
        ),
    ]
