# Generated by Django 3.2.7 on 2021-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactModel',
        ),
    ]
